name: Pre merge tests

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - main
      - development
    tags:
      - v0.*.*
  workflow_dispatch:

jobs:
  ready:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js environment ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        env:
          SNYK_API_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
        run: npm test
      - name: Snyk
        uses: snyk/actions@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}